### PR TITLE
Create hollow_diamond_pattern.c

### PR DESCRIPTION
**Pull request by Mayankjha997**
This is the hollow diamond pattern in c language.

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Hey, first thanks for contributing. I check and test your code. Found bugs that make your code not reliable to any given number, it shrink, move, or even not look like a diamond shape. Let me know if this just my compiler or a bugs that you need to fix. For example given number 20:
```
********************
**** ***************
***   **************
**     *************
*       ************
**     *************
***   **************
**** ***************
********************
********************
********************
********************
********************
********************
********************
********************
********************
********************
********************
********************
```
Or given number 10:
```
**********
**** *****
***   ****
**     ***
*       **
**     ***
***   ****
**** *****
**********
**********
```
I would like to see the star symbols separated by one space

**Comment by Mayankjha997** [comment]
This is the only shape that i made just named it as diamond shape .

**Comment by Mayankjha997** [comment]
if i will put space it won't look good. This is pattern made by me . soo please review its working fine and printing the desired pattern .Hope you will like it

**Comment by Reynadi531** [comment]
Yeah because i don't request this shape and you make it, i still accept your hard work. Thanks for contribute

**Comment by Mayankjha997** [comment]
Thank you very much for this.

**Pull request merged**
