### PR TITLE
Diamond pattern using C

### PR DESCRIPTION
**Pull request by Dilpreet047**
Print a diamond shape pattern for the given number of rows.

Output Example:
Enter number of rows
10
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
 *****************
  ***************
   *************
    ***********
     *********
      *******
       *****
        ***
         *

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Nice work, but please separate the star symbols by one space

**Comment by Dilpreet047** [comment]
> Nice work, but please separate the star symbols by one space

Okay, I'll make the changes.

**Comment by Dilpreet047** [comment]
The requested changes have been made.

**Comment by Reynadi531** [comment]
Nice, thanks for contributing

**Pull request merged**
