### PR TITLE
Create hollow_triangle.cpp

### PR DESCRIPTION
**Pull request by ruthwik3690**

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Awsome, please move your file to src/C++

**Comment by ruthwik3690** [comment]
Can you please tell me how to do that?

**Comment by Reynadi531** [comment]
you can use 
`
git mv hollow_triangle.cpp src/C++/
`
and recommit your branch

**Comment by ruthwik3690** [comment]
I don't know how to do that.😅

**Comment by Reynadi531** [comment]
Yup thanks for your latest PR

**Comment by ruthwik3690** [comment]
Yeah cool!😁

**Pull request closed without merging**
