### PR TITLE
added star pattern java program

### LINKED ISSUE #2: Add starpatten in your programing language
Make your own folder name it your programing language, and make starpattern file. Example output if given n is 5:
```
* 
* * 
* * *
* * * *
* * * * *
```
More example you can look at starpattern.js at src/javascript

### PR DESCRIPTION
**Pull request by crazyvibes**

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Please seperate the star symbols by one space like example in the issue that i give

**Comment by crazyvibes** [comment]
okay

**Comment by crazyvibes** [comment]
please check

**Comment by crazyvibes** [comment]
change the label status please:)

**Pull request merged**
