### PR TITLE
Adding SquarePattern.java

### PR DESCRIPTION
**Pull request by kots14**
**Reference** : https://github.com/Reynadi531/a-patterns/issues/6#issue-713321002  

Adding solution for Square pattern in java

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Hey, could you commented out the output of your code at the end of this file, cause i can't test java code

**Comment by kots14** [comment]
Sure. I'll mention the output as comments in the code. Hope that works. I'll update this PR accordingly.

**Comment by kots14** [comment]
@Reynadi531 I've updated the output in the file as comment. Let me know if you'd need any more changes.

**Comment by Reynadi531** [comment]
Nice. I assume that you already test and check your code. Thanks for contributing

**Pull request merged**
