### PR TITLE
added another hollowtriangle in java

### PR DESCRIPTION
**Pull request by SATAKSHI08**
i have made another program in java for hollow triangle.

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Can you comment how to call your function

**Comment by SATAKSHI08** [comment]
it is made in main function so doesn't require to be called.As it will automatically get called once you run the program.

**Comment by Reynadi531** [comment]
OK. I assume that you already check and test your code. Thanks for contribute

**Comment by SATAKSHI08** [comment]
yeah i have checked and tested the code.

**Pull request merged**
