### PR TITLE
Diamond pattern

### PR DESCRIPTION
**Pull request by rohan8660**
| C | diamond_pattern.c | rohan8660 |

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Hey i would like to see the star symbols separated by one space

**Comment by rohan8660** [comment]
Okay ,I will do it

**Comment by rohan8660** [comment]
I have made the change requested

**Comment by rohan8660** [comment]
renamed the file to avoid conflict.

**Comment by Reynadi531** [comment]
Nice work, thanks for contributing

**Comment by rohan8660** [comment]
Can you please label it "hacktoberfest accepted "

**Pull request merged**
