### PR TITLE
Added Pascal triangle pattern java

### PR DESCRIPTION
**Pull request by karshil2309**

### CODE REVIEW

**Comment by karshil2309** [comment]
Hey any problem with this pr?

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
hey nice work, but could you commented the output of your code

**Review by karshil2309 — COMMENTED** [review]
Hey there, added output in comment, pls do review. Thanks!

**Comment by Reynadi531** [comment]
Nice work, sorry for late review. Thanks for contributing

**Pull request merged**
