### PR TITLE
Inverted Number Triangle added

### PR DESCRIPTION
**Pull request by rishiraj52**
Make numbers triangle 
issue: #72

### CODE REVIEW

**Review by Reynadi531 — CHANGES_REQUESTED** [review]
Can you add the output of your code in the buttom of the file

**Comment by rishiraj52** [comment]
OK OK, I will!

**Comment by rishiraj52** [comment]
File changes made, can you review it now?

**Comment by Reynadi531** [comment]
Cool, nice work. Thank you

**Pull request merged**
